version: '3'

services:
  pg-db:
    image: postgres:16
    container_name: service-bridge-db
    ports:
      - '5555:5432'
    environment:
      POSTGRES_DB: 'servicebridge'
      POSTGRES_USER: 'servicebridge'
      POSTGRES_PASSWORD: 'servicebridge'
    volumes:
      - ./.docker-data/.pg-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: servicebridge-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq
      - ./.rabbit-plugins:/etc/rabbitmq/enabled_plugins

  service-bridge:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/service_bridge
    links:
      - pg-db:postgres
      - rabbitmq:rabbitmq
    container_name: service_bridge_1
    depends_on:
      - pg-db
      - rabbitmq
    stdin_open: true
    tty: true
    environment:
      QUART_APP: app.py
